/**
 * Type definitions cho toàn bộ database schema
 * File: src/db/schema.ts
 * Đồng bộ 100% với src/db/migrations/0001_initial_schema.sql
 */

export type TrangThaiHoSo = 'ChoRaSoat' | 'HopLe' | 'CanBoSung' | 'KhongDuDieuKien' | 'DaChinhSua';
export type TrangThaiRaSoat = 'Dat' | 'CanhBao' | 'KhongDat';
export type TrangThaiDiem = 'ChuaNhap' | 'DaNhap' | 'DaKhoa';
export type TrangThaiPhongThi = 'ChuaSapXep' | 'DaSapXep' | 'DaKhoa' | 'DaThiXong';
export type TrangThaiKy = 'Mo' | 'DangTuyen' | 'DaKhoa' | 'Huy';
export type CapHoc = 'MN' | 'TH' | 'THCS' | 'THPT' | 'GDTX' | 'DNTTHPT';
export type GioiTinh = 'Nam' | 'Nu' | 'Khac';
export type HinhThucThi = 'Viet' | 'TracNghiem' | 'ThucHanh';
export type Quyen = 'ADMIN' | 'TO_NHAP_HOSO' | 'TO_NHAP_DIEM' | 'LANH_DAO';
export type TrangThaiUser = 'HoatDong' | 'Khoa';
export type LoaiQd = 'PheDuyetDSVong1' | 'PheDuyetDSVong2' | 'PheDuyetKetQuaChinhThuc' | 'Khac';
export type KetQua = 'ChoXuLy' | 'Dat' | 'KhongDat' | 'Vang' | 'BoThi' | 'KhongDuDieuKien';
export type LoaiTemplate = 'mau_in' | 'phieu_yeu_cau' | 'bao_cao' | 'quyet_dinh';
export type TrangThaiTemplate = 'HoatDong' | 'Ngung';
export type TrangThaiImport = 'DangXuLy' | 'HoanTat' | 'Loi' | 'Huy';

// ============================================================================
// Entity types
// ============================================================================

export interface User {
  id: number;
  username: string;
  password_hash: string;
  ho_ten: string;
  email: string | null;
  quyen: Quyen;
  trang_thai: TrangThaiUser;
  last_login_at: string | null;
  created_at: string;
  updated_at: string;
}

export type UserCreate = Omit<User, 'id' | 'created_at' | 'updated_at' | 'last_login_at'>;
export type UserUpdate = Partial<Omit<User, 'id' | 'created_at' | 'updated_at'>>;

export interface KyTuyenDung {
  id: number;
  ten_ky: string;
  nam: number;
  ngay_bat_dau: string;
  ngay_ket_thuc: string;
  trang_thai: TrangThaiKy;
  mo_ta: string | null;
  created_at: string;
  updated_at: string;
}

export type KyTuyenDungCreate = Omit<KyTuyenDung, 'id' | 'created_at' | 'updated_at'>;
export type KyTuyenDungUpdate = Partial<Omit<KyTuyenDung, 'id' | 'created_at' | 'updated_at'>>;

export interface ViTriTuyenDung {
  id: number;
  ky_tuyendung_id: number;
  ma_vi_tri: string;
  mon: string;
  cap_hoc: CapHoc;
  loai_vi_tri: string;
  so_luong: number;
  hinh_thuc_thi: HinhThucThi;
  diem_chuan: number | null;
  /** JSON array thứ tự ưu tiên đồng điểm, VD: ["diem_thi_giang","doi_tuong_uu_tien","ngay_nop_ho_so"]
   * NULL = dùng mặc định: diem_thi_giang DESC → doi_tuong_uu_tien → ngay_nop_ho_so ASC
   * Confirmed không fix cứng (Anh Vũ, 18/06/2026)
   */
  thu_tu_uu_tien_dong_diem: string | null;
  ghi_chu: string | null;
  created_at: string;
  updated_at: string;
}

export type ViTriCreate = Omit<ViTriTuyenDung, 'id' | 'created_at' | 'updated_at'>;
export type ViTriUpdate = Partial<Omit<ViTriTuyenDung, 'id' | 'created_at' | 'updated_at'>>;

export interface DonViTuyenDung {
  id: number;
  ky_tuyendung_id: number;
  ma_don_vi: string;
  ten_don_vi: string;
  cap_hoc: CapHoc;
  dia_chi: string | null;
  so_dien_thoai: string | null;
  nguoi_lien_he: string | null;
  ghi_chu: string | null;
  so_chi_tieu: number;
  created_at: string;
  updated_at: string;
}

export type DonViCreate = Omit<DonViTuyenDung, 'id' | 'created_at' | 'updated_at'>;

export interface ViTriDonVi {
  id: number;
  vitri_tuyendung_id: number;
  don_vi_tuyen_dung_id: number;
  so_luong_phan_bo: number;
  created_at: string;
}

export interface ThiSinh {
  id: number;
  ky_tuyendung_id: number;
  vi_tri_dang_ky_id: number;
  don_vi_du_tuyen_id: number;
  ho: string;
  ten: string;
  ho_ten: string;
  ngay_sinh: string;
  gioi_tinh: GioiTinh;
  dan_toc: string | null;
  ho_khau_thuong_tru: string | null;
  cccd: string | null;
  ngay_cap_cccd: string | null;
  noi_cap_cccd: string | null;
  dien_thoai: string | null;
  email: string | null;
  ten_truong_dao_tao: string | null;
  trinh_do_chuyen_mon: string | null;     // Kỹ sư / Cử nhân / Cao đẳng / Trung cấp (từ "Trình độ chuyên môn" Google Form)
  chuyen_nganh: string | null;
  nam_tot_nghiep: number | null;
  co_chung_chi_nvsp: number;        // 0/1
  xep_loai_bang: string | null;
  doi_tuong_uu_tien: string | null; // CSV
  trang_thai_ho_so: TrangThaiHoSo;
  ma_ho_so: string | null;  // TDVC-YYYY-NNNNN — generated by trigger trg_thisinh_gen_ma_ho_so
  sbd: string | null;       // Số báo danh — format SBD-{SEQ:04d}, sinh khi xếp phòng
  is_profile_locked: number; // 0 = chưa khóa, 1 = đã khóa
  locked_at: string | null;
  locked_by: number | null;
  ly_do_tu_choi: string | null;
  ngay_nop_ho_so: string;
  // ----- Bổ sung từ Phiếu đăng ký Google Form (migration 0007) -----
  ngay_nop_phieu: string | null;      // Dấu thời gian từ Google Form
  ton_giao: string | null;
  suc_khoe: string | null;
  chieu_cao: string | null;
  can_nang: string | null;
  cho_o_hien_nay: string | null;
  trinh_do_van_hoa: string | null;
  so_hieu_van_bang: string | null;
  hinh_thuc_dao_tao: string | null;
  nganh_dao_tao: string | null;
  ngay_cap_van_bang: string | null;
  ngoai_ngu: string | null;
  ngoai_ngu_khac: string | null;
  mien_thi_nn: string | null;
  cam_doan_thong_tin: string | null;
  // Nguyện vọng 2
  co_dang_ky_nv2: number;             // 0/1
  vi_tri_dang_ky_id_2: number | null;
  don_vi_du_tuyen_id_2: number | null;
  // -----
  created_at: string;
  updated_at: string;
  created_by: number | null;
  updated_by: number | null;
}

export interface ThiSinhNguoiThan {
  id: number;
  thisinh_id: number;
  thu_tu: 1 | 2 | 3;
  moi_quan_he: string | null;
  ho_ten: string | null;
  ngay_sinh: string | null;
  thong_tin_khac: string | null;
  created_at: string;
}

export interface ThiSinhVanBang {
  id: number;
  thisinh_id: number;
  thu_tu: 1 | 2;
  ten_truong: string | null;
  ngay_cap: string | null;
  trinh_do: string | null;
  so_hieu: string | null;
  chuyen_nganh: string | null;
  hinh_thuc: string | null;
  nganh: string | null;
  xep_loai: string | null;
  created_at: string;
}

export interface ThiSinhQtc {
  id: number;
  thisinh_id: number;
  thu_tu: 1 | 2;
  tu_ngay: string | null;
  den_ngay: string | null;
  co_quan: string | null;
  created_at: string;
}

export interface RaSoatKetQua {
  id: number;
  thisinh_id: number;
  ky_tuyendung_id: number;
  trang_thai: TrangThaiRaSoat;
  diem_uu_tien: number;
  ly_do: string;
  ngay_ra_soat: string;
  nguoi_ra_soat: number | null;
  created_at: string;
}

export type ThiSinhCreate = Omit<ThiSinh, 'id' | 'created_at' | 'updated_at' | 'ngay_nop_ho_so' | 'created_by' | 'updated_by' | 'ma_ho_so'> & {
  created_by?: number;
  ma_ho_so?: string | null;  // optional — trigger sinh tự động nếu không cung cấp
};
export type ThiSinhUpdate = Partial<Omit<ThiSinh, 'id' | 'created_at' | 'updated_at'>>;

export interface PhongThi {
  id: number;
  ky_tuyendung_id: number;
  vi_tri_dang_ky_id: number;
  ma_phong: string;
  ten_phong: string | null;
  dia_diem: string | null;
  suc_chua: number;
  ngay_thi: string;
  gio_thi: string;
  so_luong_da_xep: number;
  trang_thai: TrangThaiPhongThi;
  ghi_chu: string | null;
  created_at: string;
  updated_at: string;
}

export interface DiemThi {
  id: number;
  thisinh_id: number;
  phongthi_id: number | null;
  diem_gk1: number | null;
  diem_gk2: number | null;
  diem_thi_giang: number | null;     // computed by trigger
  vang_thi: number;                  // 0/1
  bo_thi: number;                    // 0/1
  ly_do_vang: string | null;
  trang_thai_nhap: TrangThaiDiem;
  ngay_nhap: string | null;
  nguoi_nhap: number | null;
  ngay_khoa: string | null;
  nguoi_khoa: number | null;
  created_at: string;
  updated_at: string;
}

export type DiemThiUpdate = Partial<
  Pick<DiemThi, 'diem_gk1' | 'diem_gk2' | 'vang_thi' | 'bo_thi' | 'ly_do_vang' | 'phongthi_id'>
>;

export interface KetQuaRecord {
  id: number;
  thisinh_id: number;
  diem_thi_giang: number | null;
  diem_uu_tien: number;
  diem_tong: number;
  xep_hang: number | null;
  ket_qua: KetQua;
  ghi_chu: string | null;
  ngay_chay: string;
  nguoi_chay: number | null;
  created_at: string;
  updated_at: string;
}

export interface HistChinhSua {
  id: number;
  thisinh_id: number;
  truong: string;
  gia_tri_cu: string | null;
  gia_tri_moi: string | null;
  ly_do: string | null;
  nguoi_sua: number;
  ngay_sua: string;
}

export interface LogHeThong {
  id: number;
  user_id: number | null;
  username: string | null;
  action: string;
  resource_type: string | null;
  resource_id: number | null;
  ip_address: string | null;
  user_agent: string | null;
  payload: string | null;
  result: 'SUCCESS' | 'FAILURE';
  error_message: string | null;
  ngay_thuc_hien: string;
}

export interface QuyetDinh {
  id: number;
  ky_tuyendung_id: number;
  so_quyet_dinh: string;
  ngay_ban_hanh: string;
  tieu_de: string;
  loai_quyet_dinh: LoaiQd;
  noi_dung: string | null;
  file_dinh_kem: string | null;
  nguoi_ky: string;
  chuc_vu_nguoi_ky: string | null;
  ngay_tao: string;
  nguoi_tao: number | null;
}

export interface WordTemplate {
  id: number;
  ma_template: string;
  ten_template: string;
  file_path: string;
  mo_ta: string | null;
  loai: LoaiTemplate;
  trang_thai: TrangThaiTemplate;
  version: number;
  created_at: string;
  updated_at: string;
}

export interface CongThucXetTuyen {
  id: number;
  ky_tuyendung_id: number;
  ten_cong_thuc: string;
  bieu_thuc: string;
  mo_ta: string | null;
  is_default: number;
  created_at: string;
}

export interface SystemConfig {
  key: string;
  value: string;
  mo_ta: string | null;
  updated_at: string;
  updated_by: number | null;
}

export interface ImportBatch {
  id: number;
  ky_tuyendung_id: number;
  ten_file: string;
  kich_thuoc: number;
  so_dong: number;
  so_dong_thanh_cong: number;
  so_dong_loi: number;
  danh_sach_loi: string | null;
  nguoi_import: number;
  ngay_import: string;
  trang_thai: TrangThaiImport;
}
